__author__ = 'wolfram'

import alg_dijkstra, unittest

class TestDijkstra(unittest.TestCase):

    def test_not_connected_graph(self):
        graph = alg_dijkstra.WeightedGraph()
        graph.add_vertex(0)
        graph.add_vertex(1)
        graph.add_vertex(2)
        graph.add_vertex(3)
        graph.add_vertex(4)
        graph.add_vertex(5)
        graph.add_vertex(6)
        graph.add_vertex(7)
        graph.add_vertex(8)
        graph.add_vertex(9)
        graph.add_vertex(10)
        graph.add_direct_link(0, 1, 2)
        graph.add_direct_link(0, 2, 1)
        graph.add_direct_link(0, 5, 8)
        graph.add_direct_link(1, 2, 3)
        graph.add_direct_link(2, 3, 1)
        graph.add_direct_link(2, 4, 2)
        graph.add_direct_link(3, 6, 3)
        graph.add_direct_link(4, 5, 7)
        graph.add_direct_link(5, 6, 2)
        graph.add_direct_link(7, 8, 2)
        graph.add_direct_link(7, 9, 3)
        graph.add_direct_link(8, 10, 1)
        graph.add_direct_link(9, 10, 2)
        graph.add_direct_link(10, 7, 1)
        self.assertEqual(graph.paths(6), [[], [], [], [], [], [], [6], [], [], [], []])
        self.assertEqual(graph.paths(7), [[], [], [], [], [], [], [], [7], [7, 8], [7, 9], [7, 8, 10]])

    def test_small_graph(self):
        graph = alg_dijkstra.WeightedGraph()
        graph.add_vertex(0)
        graph.add_vertex(1)
        graph.add_vertex(2)
        graph.add_vertex(3)
        graph.add_vertex(4)
        graph.add_vertex(5)
        graph.add_vertex(6)
        graph.add_direct_link(0, 1, 2)
        graph.add_direct_link(0, 2, 1)
        graph.add_direct_link(0, 5, 8)
        graph.add_direct_link(1, 2, 3)
        graph.add_direct_link(2, 3, 1)
        graph.add_direct_link(2, 4, 2)
        graph.add_direct_link(3, 6, 3)
        graph.add_direct_link(4, 5, 7)
        graph.add_direct_link(5, 6, 2)
        self.assertEqual(graph.paths(0), [[0], [0, 1], [0, 2], [0, 2, 3], [0, 2, 4], [0, 5], [0, 2, 3, 6]])
        self.assertEqual(graph.paths(6), [[], [], [], [], [], [], [6]])
        self.assertEqual(graph.paths(3), [[], [], [], [3], [], [], [3, 6]])
        self.assertEqual(graph.paths(2), [[], [], [2], [2, 3], [2, 4], [2, 4, 5], [2, 3, 6]])